name: Deploy QuantumTrader

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh root@50.175.235.10 << 'EOF'
          cd ~/QuantumTrader
          git pull origin main
          docker compose build --no-cache
          docker compose up -d
        EOF
